### ISSUE TITLE
CubicEquationSolver and Spyder

### ISSUE THREAD

**Issue by conceptstom** [shril/CubicEquationSolver#3]
![skaermbillede 2018-11-25 03 10 33](https://user-images.githubusercontent.com/8062795/48974647-c6574400-f05e-11e8-939a-c44e94054ff4.png)

Exactly I ended up succesfully by changing the directory for the cubicequationsolver.py file and now it returs the values for the roots in the Spyder console.

But how to plot the roots graphically by using matplotlib ?
Which commands has to be run in the Spyder console for plotting the roots graphically ?

**Comment by devojoyti** [comment]
Man google it, search stackoverflow, search matplotlib documentation. 
[https://matplotlib.org/gallery/lines_bars_and_markers/simple_plot.html](https://matplotlib.org/gallery/lines_bars_and_markers/simple_plot.html)
